# Generated by Django 3.1.1 on 2020-09-09 14:23

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0003_auto_20200909_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesperson',
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'proxy': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='Client',
            name='Salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson'),
        ),
    ]
