# Generated by Django 3.1.1 on 2020-09-09 14:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0005_auto_20200909_1423'),
        ('sales', '0004_auto_20200909_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesperson',
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
