# Generated by Django 3.1.1 on 2020-09-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200909_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Salesperson',
            new_name='salesperson',
        ),
    ]
