# Generated by Django 3.1.1 on 2020-09-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='paid_until',
            new_name='paid_until_new',
        ),
    ]
